// AUTO-GENERATED from the integrations.sh catalog (kind=mcp). These are remote
// MCP servers with a live-detected streamable-HTTP/SSE endpoint and an auth
// mechanism a generic OAuth/PKCE or API-key client can use. Regenerate by
// re-running the extract against https://integrations.sh/api.json. The curated
// entries in mcp-catalog.ts take precedence and are not duplicated here.
import type { McpCatalogEntry } from "./mcp-catalog"

export const MCP_CATALOG_REGISTRY: McpCatalogEntry[] = [
  {
    slug: "canva-mcp-server",
    name: "Canva",
    description:
      "Browse, summarize, autofill, and even generate new Canva designs directly from Claude. Make Canva a native par",
    url: "https://mcp.canva.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/canva.com",
    learnMoreUrl: "https://www.canva.dev/docs/mcp/",
  },
  {
    slug: "monday-com-mcp-server",
    name: "monday.com",
    description:
      "The monday MCP server exposes core monday.com capabilities to agents. It enables actions like searching boards",
    url: "https://mcp.monday.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/monday.com",
    learnMoreUrl: "https://monday.com/w/mcp",
  },
  {
    slug: "box",
    name: "Box",
    description:
      "Ask questions about your enterprise content, get insights from unstructured data, automate content workflows,",
    url: "https://mcp.box.com",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/box.com",
    learnMoreUrl: "https://developer.box.com/guides/box-mcp",
  },
  {
    slug: "miro",
    name: "Miro",
    description:
      "Access your board content and create content inside Miro from Claude. Use your teams workshops, technical spec",
    url: "https://mcp.miro.com",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/miro.com",
    learnMoreUrl: "https://developers.miro.com/docs/miro-mcp",
  },
  {
    slug: "granola",
    name: "Granola",
    description:
      "Connect Claude to your meeting history. Ask questions about your work and use your conversation context to get",
    url: "https://mcp.granola.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/granola.ai",
    learnMoreUrl:
      "https://docs.granola.ai/help-center/sharing/integrations/mcp",
  },
  {
    slug: "microsoft-learn",
    name: "Microsoft Learn",
    description:
      "The Microsoft Learn MCP Server enables clients like GitHub Copilot and other AI agents to bring trusted and up",
    url: "https://learn.microsoft.com/api/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/microsoft.com",
    learnMoreUrl: "https://learn.microsoft.com/en-us/graph/mcp-server/overview",
  },
  {
    slug: "zoom-for-claude-mcp-server",
    name: "Zoom for Claude",
    description:
      "The Zoom for Claude connector allows users to search their Zoom meetings using natural language, retrieve meet",
    url: "https://mcp.zoom.us/mcp/zoom/streamable",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/zoom.com",
    learnMoreUrl: "https://developers.zoom.us/docs/integrations/oauth/",
  },
  {
    slug: "indeed",
    name: "Indeed",
    description:
      "Search and retrieve job listings, access detailed job descriptions and requirements, and provide direct job li",
    url: "https://mcp.indeed.com/claude/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/indeed.com",
    learnMoreUrl: "https://docs.indeed.com/mcp/",
  },
  {
    slug: "clickup",
    name: "ClickUp",
    description:
      "The ClickUp connector enables secure, real-time interaction between AI agents like Claude and your ClickUp wor",
    url: "https://mcp.clickup.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/clickup.com",
    learnMoreUrl:
      "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
  },
  {
    slug: "ahrefs",
    name: "Ahrefs",
    description:
      "Research keywords, analyze backlinks, track rankings, and monitor brand visibility across traditional search a",
    url: "https://api.ahrefs.com/mcp/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/ahrefs.com",
    learnMoreUrl: "https://docs.ahrefs.com/en/mcp/docs/introduction",
  },
  {
    slug: "clay",
    name: "Clay",
    description:
      "Prospect with Clay inside Claude: run deep company and contact research without leaving your conversation. Use",
    url: "https://api.clay.com/v3/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/clay.com",
    learnMoreUrl: "https://university.clay.com/docs/mcp-settings",
  },
  {
    slug: "apollo-io",
    name: "Apollo",
    description:
      "Connect Apollo to Claude so you can prospect and take action from a single conversation. Search Apollo's datab",
    url: "https://mcp.apollo.io/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/apollo.io",
    learnMoreUrl: "https://docs.apollo.io/docs/apollo-mcp",
  },
  {
    slug: "kensho-llm-ready-api-remote-mcp",
    name: "Kensho LLM-Ready API Remote",
    description:
      "Use natural language to query a range of S&P Global datasets, including S&P Capital IQ Financials, S&P Capital",
    url: "https://kfinance.kensho.com/integrations/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/kensho.com",
    learnMoreUrl: "https://docs.kensho.com/llmreadyapi/mcp",
  },
  {
    slug: "adaptive-retrieval-mcp",
    name: "Adaptive Retrieval",
    description:
      "Use natural language to query a range of S&P Global datasets, including S&P Capital IQ Financials, S&P Capital",
    url: "https://grounding.kensho.com/integrations/v2/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/kensho.com",
    learnMoreUrl: "https://docs.kensho.com/adaptive-retrieval/mcp",
  },
  {
    slug: "wordpress-com-mcp-server",
    name: "WordPress.com",
    description:
      "Manage and create on your WordPress site through a conversation with Claude. Ask Claude to find a post, check",
    url: "https://public-api.wordpress.com/wpcom/v2/mcp/v1",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/wordpress.com",
    learnMoreUrl: "https://developer.wordpress.com/docs/mcp/",
  },
  {
    slug: "google-cloud-bigquery",
    name: "Google Cloud BigQuery",
    description:
      "Integrate analytical data into your agent workflows to achieve superior business results. By connecting your a",
    url: "https://bigquery.googleapis.com/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/bigquery.googleapis.com",
    learnMoreUrl:
      "https://docs.cloud.google.com/bigquery/docs/use-bigquery-mcp",
  },
  {
    slug: "spotify",
    name: "Spotify",
    description:
      "Explore a new way to discover music and podcasts, with recommendations that are uniquely you. Want music to po",
    url: "https://mcp-gateway-external-pilot.spotify.net/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/spotify.net",
    learnMoreUrl: "https://mcp-gateway-external-pilot.spotify.net/mcp",
  },
  {
    slug: "windsor-mcp",
    name: "Windsor",
    description:
      "Analyze multi-channel marketing, analytics, sales, and e-commerce data within Claude by connecting to your Win",
    url: "https://mcp.windsor.ai",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/windsor.ai",
    learnMoreUrl: "https://mcp.windsor.ai/",
  },
  {
    slug: "posthog-mcp-server",
    name: "PostHog",
    description:
      "Connect to PostHog and work with your product data through natural conversation. Query analytics using HogQL o",
    url: "https://mcp.posthog.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/posthog.com",
    learnMoreUrl: "https://posthog.com/docs/model-context-protocol",
  },
  {
    slug: "pendo-mcp-server",
    name: "Pendo",
    description:
      "The Pendo connector for product analytics and behavioral data to AI environments. Access visitor and account m",
    url: "https://app.pendo.io/mcp/v0/shttp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/pendo.io",
    learnMoreUrl:
      "https://support.pendo.io/hc/en-us/articles/41102236924955-Connect-to-the-Pendo-MCP-server",
  },
  {
    slug: "netlify-mcp-server",
    name: "Netlify",
    description:
      "Create, deploy, and manage websites on Netlify. You'll be able to control all aspects of your site from creati",
    url: "https://netlify-mcp.netlify.app/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/netlify-mcp.netlify.app",
    learnMoreUrl:
      "https://docs.netlify.com/build/build-with-ai/agent-setup-guides/agent-setup-overview/",
  },
  {
    slug: "hex-mcp-server",
    name: "Hex",
    description:
      "Connect to your Hex workspace to get data insights directly in Claude. Find Hex projects and answer questions",
    url: "https://app.hex.tech/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/hex.tech",
    learnMoreUrl: "https://learn.hex.tech/docs/api-integrations/mcp-server",
  },
  {
    slug: "wix-mcp-server",
    name: "Wix",
    description:
      "The Wix MCP provides users with the ability to manage their account's websites and apps (Stores, Bookings, Blo",
    url: "https://mcp.wix.com/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/wix.com",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl:
      "https://dev.wix.com/docs/sdk/articles/use-the-wix-mcp/about-the-wix-mcp",
  },
  {
    slug: "consensus-mcp",
    name: "Consensus",
    description:
      "Consensus enables AI assistants to search through 200+ million peer-reviewed research papers from leading acad",
    url: "https://mcp.consensus.app/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/consensus.app",
    learnMoreUrl: "https://docs.consensus.app/docs/mcp",
  },
  {
    slug: "scholar-gateway-mcp",
    name: "Scholar Gateway",
    description:
      "Scholar Gateway enables Claude to generate responses grounded in peer-reviewed sources with verifiable citatio",
    url: "https://connector.scholargateway.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/scholargateway.ai",
    learnMoreUrl: "https://docs.scholargateway.ai/",
  },
  {
    slug: "outreach-mcp-server",
    name: "Outreach",
    description:
      "Bring Outreach knowledge and actions into Claude so your teams can move faster, combine insights across system",
    url: "https://api.outreach.io/mcp/",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/outreach.io",
    learnMoreUrl: "https://developers.outreach.io/mcp-server",
  },
  {
    slug: "morningstar-mcp-server",
    name: "Morningstar",
    description:
      "The Morningstar connector makes it simple to power your AI apps and tools with Morningstar’s trusted content.",
    url: "https://mcp.morningstar.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/morningstar.com",
    learnMoreUrl:
      "https://developer.morningstar.com/direct-web-services/documentation/morningstar-mcp-server/about",
  },
  {
    slug: "daloopa-mcp-server",
    name: "Daloopa",
    description:
      "Daloopa supplies high quality fundamental data sourced from SEC Filings, investor presentations and any public",
    url: "https://mcp.daloopa.com/server/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/daloopa.com",
    learnMoreUrl: "https://docs.daloopa.com/docs/daloopa-mcp",
  },
  {
    slug: "booking-com-demand-api-mcp-server",
    name: "Booking.com Demand API",
    description:
      "Get your trip started with Booking.com directly on Claude. Search, compare, and find your next stay – from a p",
    url: "https://demandapi-mcp.booking.com/v1/mcp/8132308",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/booking.com",
    learnMoreUrl: "https://developers.booking.com/mcp/booking-connector/about",
  },
  {
    slug: "fathom-mcp-server",
    name: "Fathom",
    description:
      "Access your meeting summaries, transcripts, and action items so you can ask questions and build deliverables g",
    url: "https://api.fathom.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/fathom.ai",
    learnMoreUrl: "https://developers.fathom.ai/mcp-docs",
  },
  {
    slug: "incident-io-mcp-server",
    name: "incident.io",
    description:
      "Manage your full incident.io workspace from one place. Declare and triage incidents, ack pages, check who's on",
    url: "https://mcp.incident.io/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/incident.io",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://docs.incident.io/ai/remote-mcp",
  },
  {
    slug: "attio-mcp-server",
    name: "Attio",
    description:
      "Access your entire CRM directly from Claude. Look up contacts and companies, find decision makers, and discove",
    url: "https://mcp.attio.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/attio.com",
    learnMoreUrl: "https://docs.attio.com/mcp/overview",
  },
  {
    slug: "supermetrics-marketing-analytics-mcp",
    name: "Supermetrics Marketing Analytics",
    description:
      "Supermetrics gives Claude direct access to your marketing, advertising, analytics, sales, CRM and ecommerce da",
    url: "https://mcp.supermetrics.com/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/supermetrics.com",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://mcp.supermetrics.com/docs",
  },
  {
    slug: "brex-mcp-server",
    name: "Brex",
    description:
      "Connect Brex to Claude for automating your company's finances. Finance monitors compliance and runs powerful q",
    url: "https://api.brex.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/brex.com",
    learnMoreUrl: "https://developer.brex.com/docs/mcp",
  },
  {
    slug: "omni-analytics-mcp-server",
    name: "Omni Analytics",
    description:
      "Query Omni using the same semantic model, permissions, and logic defined by your data team directly from Claud",
    url: "https://callbacks.omniapp.co/callback/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/omniapp.co",
    learnMoreUrl: "https://docs.omni.co/ai/mcp/authentication",
  },
  {
    slug: "crossbeam-mcp-server",
    name: "Crossbeam",
    description:
      "Connect your Claude workspace to Crossbeam and bring Ecosystem Intelligence into every AI workflow. The Crossb",
    url: "https://mcp.crossbeam.com",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/crossbeam.com",
    learnMoreUrl:
      "https://help.crossbeam.com/en/articles/12601327-crossbeam-mcp-server-limited-availability",
  },
  {
    slug: "base44-mcp-server",
    name: "Base44",
    description:
      "Create, edit, and manage Base44 apps directly from Claude. Describe what you want to build and Base44 will gen",
    url: "https://app.base44.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/base44.com",
    learnMoreUrl:
      "https://docs.base44.com/developers/backend/overview/mcp-server",
  },
  {
    slug: "moody-s-mcp-server",
    name: "Moody's",
    description:
      "Moody's GenAI-Ready Data powers AI applications with access to Moody's Ratings proprietary credit ratings, res",
    url: "https://api.moodys.com/genai-ready-data/m1/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/moodys.com",
    learnMoreUrl:
      "https://www.moodys.com/web/en/us/genai/model-context-protocol.html",
  },
  {
    slug: "superhuman-mail-mcp-server",
    name: "Superhuman Mail",
    description:
      "Connect Superhuman Mail to Claude, and build powerful workflows for email and calendar. Find anything in your",
    url: "https://mcp.mail.superhuman.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/superhuman.com",
    learnMoreUrl:
      "https://help.superhuman.com/hc/en-us/articles/46005696690317-Superhuman-Mail-MCP-Server",
  },
  {
    slug: "model-context-protocol-docs-mcp-server",
    name: "Model Context Protocol docs",
    description:
      "Ask Claude to generate and play some sheet music for you with a visual component.",
    url: "https://modelcontextprotocol.io/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/modelcontextprotocol.io",
    learnMoreUrl: "https://modelcontextprotocol.io/docs/getting-started/intro",
  },
  {
    slug: "model-context-protocol-docs-mcp-server-mintlify-host",
    name: "Model Context Protocol docs MCP server (",
    description:
      "Ask Claude to generate and play some sheet music for you with a visual component.",
    url: "https://mcp.main-kill-isr.mintlify.me/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/modelcontextprotocol.io",
    learnMoreUrl: "https://modelcontextprotocol.io/docs/getting-started/intro",
  },
  {
    slug: "airops-mcp-server",
    name: "AirOps",
    description: "Access your workspaces, Brand Kits, and AEO analytics",
    url: "https://app.airops.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/airops.com",
    learnMoreUrl: "https://docs.airops.com/mcp/mcp-server",
  },
  {
    slug: "cdata-connect-ai-mcp",
    name: "CData Connect AI",
    description:
      "Connect Claude to read, write, and act on 350+ enterprise data sources like Salesforce, Snowflake and NetSuite",
    url: "https://mcp.cloud.cdata.com/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/cdata.com",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://docs.cloud.cdata.com/en/API/MCP",
  },
  {
    slug: "cdata-connect-ai-management-mcp",
    name: "CData Connect AI Management",
    description:
      "Connect Claude to read, write, and act on 350+ enterprise data sources like Salesforce, Snowflake and NetSuite",
    url: "https://mcp.cloud.cdata.com/mcp/mgmt",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/cdata.com",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://docs.cloud.cdata.com/en/API/MCP-Management",
  },
  {
    slug: "egnyte-mcp-server",
    name: "Egnyte",
    description:
      "Egnyte MCP server enables AI agents to securely search, retrieve, and analyze content stored in any Egnyte dom",
    url: "https://mcp-server.egnyte.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/egnyte.com",
    learnMoreUrl: "https://developers.egnyte.com/docs/Remote_MCP_Server",
  },
  {
    slug: "circleback-mcp-server",
    name: "Circleback",
    description:
      "Bring context from Circleback into Claude. Search and access meeting notes, transcripts, calendar events, emai",
    url: "https://app.circleback.ai/api/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/circleback.ai",
    learnMoreUrl: "https://circleback.ai/docs/mcp",
  },
  {
    slug: "common-room-mcp-server",
    name: "Common Room",
    description:
      "Embed complete buyer intelligence directly within Claude. Research accounts and contacts, surface buying signa",
    url: "https://mcp.commonroom.io/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/commonroom.io",
    learnMoreUrl:
      "https://www.commonroom.io/docs/using-common-room/mcp-server/",
  },
  {
    slug: "tavily-remote-mcp-server",
    name: "Tavily Remote",
    description:
      "Give Claude real-time web access with Tavily. One API for search, extraction, and research. Built for the accu",
    url: "https://mcp.tavily.com/mcp/",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/tavily.com",
    learnMoreUrl: "https://docs.tavily.com/documentation/mcp",
  },
  {
    slug: "jam-mcp-server",
    name: "Jam",
    description:
      "Jam's MCP is the fast lane between Jam recordings and your dev tools. Drop a Jam link into VS Code, Cursor, Wi",
    url: "https://mcp.jam.dev/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/jam.dev",
    learnMoreUrl: "https://jam.dev/docs/jam-mcp",
  },
  {
    slug: "sanity-mcp-server",
    name: "Sanity",
    description:
      "Create, query, and manage your structured content in Sanity directly from Claude. Run content audits, update d",
    url: "https://mcp.sanity.io",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/sanity.io",
    learnMoreUrl: "https://www.sanity.io/docs/ai/mcp-server",
  },
  {
    slug: "pylon-mcp-server",
    name: "Pylon",
    description:
      "Access Pylon's customer support platform directly from Claude to search, manage, and resolve customer issues.",
    url: "https://mcp.usepylon.com",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/usepylon.com",
    learnMoreUrl: "https://docs.usepylon.com/pylon-docs/integrations/pylon-mcp",
  },
  {
    slug: "lusha-mcp-server",
    name: "Lusha",
    description:
      "The Lusha MCP Server brings enterprise-grade B2B contact and company data directly to your AI conversations. B",
    url: "https://mcp.lusha.com",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/lusha.com",
    learnMoreUrl: "https://docs.lusha.com/mcp-docs",
  },
  {
    slug: "gainsight-staircase-ai-mcp-server",
    name: "Gainsight (Staircase AI)",
    description:
      "Bring in live customer intelligence from Gainsight's Staircase AI including customer sentiment, risk, engageme",
    url: "https://mcp.staircase.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/staircase.ai",
    learnMoreUrl:
      "https://support.gainsight.com/Staircase_AI/Staircase_AI_Features/Connect_Staircase_AI_to_LLMs_Using_MCP",
  },
  {
    slug: "midpage-legal-research-mcp",
    name: "Midpage Legal Research",
    description:
      "Connect Claude to a database of case law. With the Midpage MCP, Claude can conduct complex legal research, rev",
    url: "https://app.midpage.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/midpage.ai",
    learnMoreUrl: "https://docs.midpage.ai/documentation/integration/mcp-tools",
  },
  {
    slug: "gusto-mcp-server",
    name: "Gusto",
    description:
      "Connect Claude to your Gusto account to query and analyze your payroll and people data. Ask questions in natur",
    url: "https://mcp.api.gusto.com/anthropic",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/gusto.com",
    learnMoreUrl: "https://gusto.com/product/integrations/gusto-mcp",
  },
  {
    slug: "honeycomb-mcp",
    name: "Honeycomb",
    description:
      "Query and explore observability data from OpenTelemetry or dozens of other sources in your honeycomb.io accoun",
    url: "https://mcp.honeycomb.io/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/honeycomb.io",
    learnMoreUrl:
      "https://docs.honeycomb.io/integrations/mcp/configuration-guide",
  },
  {
    slug: "enterpret-mcp-server",
    name: "Enterpret",
    description:
      "Turn customer feedback into answers you can act on, directly in Claude. Query your Enterpret knowledge graph a",
    url: "https://wisdom-api.enterpret.com/server/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/enterpret.com",
    learnMoreUrl:
      "https://helpcenter.enterpret.com/en/articles/12665166-enterpret-mcp-server",
  },
  {
    slug: "krisp-mcp",
    name: "Krisp",
    description:
      "Connect your meeting history to AI tools so past decisions, action items, and conversation context are easy to",
    url: "https://mcp.krisp.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/krisp.ai",
    learnMoreUrl:
      "https://help.krisp.ai/hc/en-us/articles/25396920405148-Krisp-MCP",
  },
  {
    slug: "synapse-mcp-server",
    name: "Synapse",
    description:
      "Discover and explore scientific datasets from collaborative research projects. Search Synapse for genomics, im",
    url: "https://mcp.synapse.org/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/synapse.org",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl:
      "https://python-docs.synapse.org/en/stable/guides/synapse_mcp/",
  },
  {
    slug: "otter-mcp-server",
    name: "Otter",
    description:
      "Otter's MCP Server integrates with Otter.ai's meeting intelligence platform, enabling users to search meeting",
    url: "https://mcp.otter.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/otter.ai",
    learnMoreUrl:
      "https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server",
  },
  {
    slug: "vianexus-vast-mcp-server",
    name: "viaNexus vAST",
    description:
      "MT Newswires' MCP server delivers real-time, low-latency financial news across equities, fixed income, commodi",
    url: "https://vast-mcp.blueskyapi.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/blueskyapi.com",
    learnMoreUrl: "https://console.blueskyapi.com/docs/vast",
  },
  {
    slug: "mem-mcp",
    name: "Mem",
    description:
      "Give Claude the full context of your second brain by connecting your Mem knowledge base. Search your AI notebo",
    url: "https://mcp.mem.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/mem.ai",
    learnMoreUrl: "https://docs.mem.ai/mcp/overview",
  },
  {
    slug: "magic-patterns-mcp-server",
    name: "Magic Patterns",
    description:
      "Discuss and iterate on Magic Patterns designs directly from Claude. Magic Patterns is an AI agent specialized",
    url: "https://mcp.magicpatterns.com/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/magicpatterns.com",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl:
      "https://www.magicpatterns.com/docs/documentation/features/mcp-server/overview",
  },
  {
    slug: "mailerlite-mcp-server",
    name: "MailerLite",
    description:
      "Connect Claude with MailerLite to create your very own email assistant. Use it to build email, analyze campaig",
    url: "https://mcp.mailerlite.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/mailerlite.com",
    learnMoreUrl: "https://developers.mailerlite.com/mcp",
  },
  {
    slug: "close-mcp-server",
    name: "Close",
    description:
      "The Close MCP server is a secure, standardized interface that lets Claude directly access and interact with yo",
    url: "https://mcp.close.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/close.com",
    learnMoreUrl: "https://developer.close.com/mcp",
  },
  {
    slug: "quartr-mcp-server",
    name: "Quartr",
    description:
      "Access structured first-party IR data from over 14,500+ public companies across 65 markets. Quartr delivers li",
    url: "https://mcp.quartr.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/quartr.com",
    learnMoreUrl: "https://mcp.quartr.com/docs",
  },
  {
    slug: "legalzoom-mcp-server",
    name: "LegalZoom",
    description:
      "AI-powered document review meets attorney guidance. Connect to LegalZoom for real-time scans of legal document",
    url: "https://www.legalzoom.com/mcp/claude/v1",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/legalzoom.com",
    learnMoreUrl: "https://www.legalzoom.com/",
  },
  {
    slug: "harmonic-mcp-server",
    name: "Harmonic",
    description:
      "Search, enrich, and research startups and companies using Harmonic's proprietary data on millions of companies",
    url: "https://mcp.api.harmonic.ai",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/harmonic.ai",
    learnMoreUrl:
      "https://support.harmonic.ai/en/articles/12785899-harmonic-mcp-server-getting-started-guide",
  },
  {
    slug: "peec-ai-mcp-server",
    name: "Peec AI",
    description:
      "Monitor and analyze your brand's visibility across AI search engines. Track your visibility, sentiment, and sh",
    url: "https://api.peec.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/peec.ai",
    learnMoreUrl: "https://docs.peec.ai/mcp/introduction",
  },
  {
    slug: "lunarcrush-mcp-server",
    name: "LunarCrush",
    description:
      "Access comprehensive social analytics and market intelligence for companies, brands, stocks, and cryptocurrenc",
    url: "https://lunarcrush.ai/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/lunarcrush.ai",
    learnMoreUrl: "https://lunarcrush.com/en/developers/mcp",
  },
  {
    slug: "fiscal-ai-mcp-server",
    name: "Fiscal.ai",
    description:
      "Access institutional-grade financial data directly within Claude. Fiscal.ai delivers fundamental metrics and r",
    url: "https://api.fiscal.ai/mcp/sse",
    transport: "sse",
    authType: "oauth",
    icon: "https://integrations.sh/logo/fiscal.ai",
    learnMoreUrl: "https://docs.fiscal.ai/docs/guides/mcp-integration",
  },
  {
    slug: "fiscal-ai-mcp-server-streamable-http",
    name: "Fiscal.ai MCP server (Streamable HTTP)",
    description:
      "Access institutional-grade financial data directly within Claude. Fiscal.ai delivers fundamental metrics and r",
    url: "https://api.fiscal.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/fiscal.ai",
    learnMoreUrl: "https://docs.fiscal.ai/docs/guides/mcp-integration",
  },
  {
    slug: "candid-mcp-server",
    name: "Candid",
    description:
      "Bring the power of Candid's comprehensive nonprofit and funder data directly into Claude. Search millions of o",
    url: "https://mcp.candid.org/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/candid.org",
    learnMoreUrl:
      "https://learning.candid.org/getting-started-with-the-candid-mcp-connector?reg=1",
  },
  {
    slug: "grain-mcp-server",
    name: "Grain",
    description:
      "Grain records and transcribes your meetings across Google Meet, Zoom, Microsoft Teams, and Webex—generating tr",
    url: "https://api.grain.com/_/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/grain.com",
    learnMoreUrl: "https://developers.grain.com/mcp",
  },
  {
    slug: "tropic-mcp-server",
    name: "Tropic",
    description:
      "Software + AI pricing isn't public, so searching the internet won't tell you if you're overpaying. Tropic will",
    url: "https://app.tropicapp.io/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/tropicapp.io",
    learnMoreUrl:
      "https://help.tropicapp.io/hc/en-us/articles/45502083594267-Using-Model-Context-Protocol-MCP-with-Tropic",
  },
  {
    slug: "ifttt-mcp-server",
    name: "IFTTT",
    description:
      "Connect IFTTT to Claude to run actions, query data, and manage your automations across 1,000+ services. Claude",
    url: "https://ifttt.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/ifttt.com",
    learnMoreUrl: "https://ifttt.com/mcp",
  },
  {
    slug: "dovetail-mcp-server",
    name: "Dovetail",
    description:
      "Connect Dovetail inside Claude to turn customer feedback into decisions without leaving your conversation. Sea",
    url: "https://dovetail.com/api/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/dovetail.com",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://developers.dovetail.com/docs/mcp",
  },
  {
    slug: "campfire-mcp-server",
    name: "Campfire",
    description:
      "Search, analyze, and retrieve data from your Campfire ERP directly in Claude. Ask questions about projects, co",
    url: "https://api.meetcampfire.com/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/campfire.ai",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://docs.campfire.ai/guides/ai-integration",
  },
  {
    slug: "contentsquare-mcp-server",
    name: "Contentsquare",
    description:
      "Quickly understand everything your users are doing and why, directly from Claude. Contentsquare automatically",
    url: "https://api.contentsquare.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/contentsquare.com",
    learnMoreUrl:
      "https://support.contentsquare.com/hc/en-us/articles/41563169756945-How-to-set-up-and-use-Model-Context-Protocol-MCP",
  },
  {
    slug: "day-ai-mcp-server",
    name: "Day AI",
    description:
      "Day AI is an AI-Native CRM that transforms emails, chats and meetings into richly-structured CRM data, stored",
    url: "https://day.ai/api/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/day.ai",
    learnMoreUrl: "https://day.ai/mcp",
  },
  {
    slug: "google-compute-engine-mcp-server",
    name: "Google Compute Engine",
    description:
      "Enables you to agentically manage your cloud compute infrastructure spanning deployment and operations.",
    url: "https://compute.googleapis.com/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/compute.googleapis.com",
    learnMoreUrl: "https://cloud.google.com/docs",
  },
  {
    slug: "motion-creative-analytics-mcp",
    name: "Motion Creative Analytics",
    description:
      "Motion connects Claude to your meta ad data. Analyze creative performance across campaigns — surface top perfo",
    url: "https://projects.motionapp.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/motionapp.com",
    learnMoreUrl: "https://help.motionapp.com/en/articles/14315735-motion-mcp",
  },
  {
    slug: "local-falcon-mcp-server",
    name: "Local Falcon",
    description:
      "Local Falcon gives Claude access to real-time local search data across Google Maps, Apple Maps, and AI search",
    url: "https://mcp.localfalcon.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/localfalcon.com",
    learnMoreUrl: "https://localfalcon.com/mcp",
  },
  {
    slug: "clarify-mcp-server",
    name: "Clarify",
    description:
      "Retrieve, create, and update records using natural language. Analyze your sales pipeline, create tasks and lis",
    url: "https://api.clarify.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/clarify.ai",
    learnMoreUrl: "https://www.clarify.ai/integrations/mcp",
  },
  {
    slug: "healthex-mcp-server",
    name: "HealthEx",
    description:
      "HealthEx connects Claude to your health records, enabling personalized insights and proactive health managemen",
    url: "https://api.healthex.io/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/healthex.io",
    learnMoreUrl: "https://docs.healthex.io/mcp-server/",
  },
  {
    slug: "scite-mcp-server",
    name: "Scite",
    description:
      "Scite delivers answers grounded in peer-reviewed research you can verify. Each response is backed by real scie",
    url: "https://api.scite.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/scite.ai",
    learnMoreUrl: "https://scite.ai/mcp",
  },
  {
    slug: "digits-mcp-server",
    name: "Digits",
    description:
      "Turn your Digits financials into a live data feed for Claude. Get instant answers about transactions, balances",
    url: "https://api.digits.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/digits.com",
    learnMoreUrl: "https://help.digits.com/business-connections/digits-mcp",
  },
  {
    slug: "cb-insights-mcp-server",
    name: "CB Insights",
    description:
      "Unleash Claude as your private markets research agent. Source companies, build market maps, draft investment m",
    url: "https://mcp.cbinsights.com",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/cbinsights.com",
    learnMoreUrl: "https://api-docs.cbinsights.com/portal/docs/CBI-MCP-Server",
  },
  {
    slug: "signnow-mcp-server",
    name: "SignNow",
    description:
      "Get documents signed faster without switching between tools. The SignNow MCP server connects Claude directly t",
    url: "https://mcp-server.signnow.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/signnow.com",
    learnMoreUrl: "https://docs.signnow.com/docs/signnow/mcp-server",
  },
  {
    slug: "sybill-mcp-server",
    name: "Sybill",
    description:
      "Sybill is the context layer for your revenue org. Connect it to Claude and ask anything about your sales conve",
    url: "https://mcp.sybill.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/sybill.ai",
    learnMoreUrl: "https://sybill.ai/llms.txt",
  },
  {
    slug: "surveymonkey-mcp-server",
    name: "SurveyMonkey",
    description:
      "Build surveys, analyze responses, and uncover trends in SurveyMonkey—right from Claude. Turn feedback into cle",
    url: "https://mcp.surveymonkey.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/surveymonkey.com",
    learnMoreUrl:
      "https://www.surveymonkey.com/apps/BKcduxPnkCN4NFCRokUYCw_3D_3D/details/",
  },
  {
    slug: "lorikeet-mcp-server",
    name: "Lorikeet",
    description:
      "Lorikeet is a platform that complex and regulated businesses use to provide their customers with a universal c",
    url: "https://api.lorikeetcx.ai/v1/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/lorikeetcx.ai",
    learnMoreUrl: "https://www.lorikeetcx.ai/integrations/mcp",
  },
  {
    slug: "stytch-mcp-server",
    name: "Stytch",
    description:
      "The Stytch MCP Server enables AI assistants to programmatically manage your Stytch Project like Redirect URLs,",
    url: "https://mcp.stytch.dev/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/stytch.dev",
    learnMoreUrl:
      "https://stytch.com/docs/resources/workspace-management/stytch-mcp-server",
  },
  {
    slug: "docuseal-mcp-server",
    name: "DocuSeal",
    description:
      "DocuSeal lets you create document templates, send them for signing, and track submission status — all through",
    url: "https://docuseal.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/docuseal.com",
    learnMoreUrl:
      "https://www.docuseal.com/guides/integrate-with-ai-agents-using-mcp",
  },
  {
    slug: "quo-mcp-server",
    name: "Quo",
    description:
      "Quo is a next-generation business phone system that helps teams engage customers, collaborate internally, and",
    url: "https://mcp.quo.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/quo.com",
    learnMoreUrl:
      "https://support.quo.com/core-concepts/integrations/mcp/other-ai-agents",
  },
  {
    slug: "fever-event-discovery-mcp-server",
    name: "Fever Event Discovery",
    description:
      "Discover and explore live entertainment experiences worldwide through Fever. Search events by city, date, loca",
    url: "https://data-search.apigw.feverup.com/mcp/",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/feverup.com",
    learnMoreUrl: "https://developer.feverup.com/en/",
  },
  {
    slug: "tango-mcp-server",
    name: "Tango",
    description:
      "The Tango server gives AI agents access to reliable, LLM-friendly federal procurement competitive intelligence",
    url: "https://govcon.dev/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/govcon.dev",
    learnMoreUrl: "https://docs.makegov.com/mcp/",
  },
  {
    slug: "send-mcp-server",
    name: "Send",
    description:
      "Create documents, one-pagers, decks, and presentations directly inside Claude. No extra subscriptions, no swit",
    url: "https://www.send.co/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/send.co",
    learnMoreUrl: "https://www.send.co/mcp/docs",
  },
  {
    slug: "ketryx-mcp-server",
    name: "Ketryx",
    description:
      "Ketryx MCP gives your AI tools direct access to your unified compliance data. Ask a compliance question and ge",
    url: "https://app.ketryx.com/api/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/ketryx.com",
    learnMoreUrl: "https://docs.ketryx.com",
  },
  {
    slug: "jentic-remote-mcp-server",
    name: "Jentic Remote",
    description:
      "Jentic connects Claude to 1,500+ APIs through a single MCP server. Credentials never touch your prompts — Jent",
    url: "https://api.jentic.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/jentic.com",
    learnMoreUrl: "https://docs.jentic.com/guides/mcp/remote-mcp/",
  },
  {
    slug: "coupler-io-mcp-server",
    name: "Coupler.io",
    description:
      "Key features: * Access data via natural language: Analyze data without SQL or coding skills. Connect to hundre",
    url: "https://mcp.coupler.io/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/coupler.io",
    learnMoreUrl: "https://www.coupler.io/mcp",
  },
  {
    slug: "b12-website-generator-mcp",
    name: "B12",
    description:
      "This extension allows you to create a professional, engaging, and user-friendly website in seconds using AI. T",
    url: "https://b12.io/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/b12.io",
    learnMoreUrl: "https://www.b12.io/ai-directory/website-generator-mcp/",
  },
  {
    slug: "adobe-journey-optimizer-mcp",
    name: "Adobe Journey Optimizer",
    description:
      "Adobe Acrobat for ChatGPT helps you transform and organize documents seamlessly. Edit, reorder, rotate, split,",
    url: "https://ajo-mcp.adobe.io/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/adobe.io",
    learnMoreUrl: "https://www.adobe.io/",
  },
  {
    slug: "alpic-mcp-server",
    name: "Alpic",
    description:
      "Access your Noodle Seed workspace in ChatGPT to find information faster, stay organized, and keep your work mo",
    url: "https://mcp.alpic.ai",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/alpic.live",
    learnMoreUrl: "https://docs.alpic.ai/developer-tools/mcp",
  },
  {
    slug: "amplitude-mcp-server",
    name: "Amplitude",
    description:
      "Connect your AI workflows to Amplitude's powerful behavior analytics and experimentation platform. The Amplitu",
    url: "https://mcp.amplitude.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/amplitude.com",
    learnMoreUrl: "https://amplitude.com/docs/en/amplitude-ai/amplitude-mcp",
  },
  {
    slug: "tinman-ai-mcp-server",
    name: "Tinman AI",
    description:
      "Tinman AI helps loan officers and underwriters quickly underwrite home financing scenarios and answer complex",
    url: "https://prod.bettermg.com/api/mortgage/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/bettermg.com",
    learnMoreUrl: "https://prod.bettermg.com/api/mortgage/mcp",
  },
  {
    slug: "bluesuite-mcp-server",
    name: "BlueSuite",
    description:
      "Manage your home service business directly from ChatGPT. BlueSuite lets you look up contacts, create and send",
    url: "https://my.bluesuite.app/api/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/bluesuite.app",
    learnMoreUrl: "https://www.bluesuite.app/chatgpt-app/",
  },
  {
    slug: "cortenoi-mcp-server",
    name: "Cortenoi",
    description:
      "Scopri Corte Noi a Bitetto con un’esperienza informativa elegante e immediata: panoramica della struttura stor",
    url: "https://cortenoi-mcp-299405366082.europe-west1.run.app/mcp",
    transport: "sse",
    authType: "none",
    icon: "https://integrations.sh/logo/cortenoi-mcp-299405366082.europe-west1.run.app",
    learnMoreUrl: "https://cortenoi-mcp-299405366082.europe-west1.run.app/",
  },
  {
    slug: "crbonfree-mcp-server",
    name: "Crbonfree",
    description:
      "CrbonFree helps people estimate and offset the carbon footprint of everyday purchases. Enter what you bought (",
    url: "https://crbonfree-mcp-server.vercel.app/mcp",
    transport: "sse",
    authType: "none",
    icon: "https://integrations.sh/logo/crbonfree-mcp-server.vercel.app",
    learnMoreUrl: "https://carbon-offset-frontend-dusky.vercel.app/",
  },
  {
    slug: "cvpop-mcp-server",
    name: "CVpop",
    description:
      "CVpop lets you create and customize professional CVs directly from ChatGPT. Describe your background and caree",
    url: "https://cvpop-mcp-server.fly.dev/mcp",
    transport: "sse",
    authType: "none",
    icon: "https://integrations.sh/logo/cvpop-mcp-server.fly.dev",
    learnMoreUrl: "https://cvpop-mcp-server.fly.dev/mcp",
  },
  {
    slug: "demandbase-mcp",
    name: "Demandbase",
    description:
      "Demandbase integration with ChatGPT gives sales, marketing, and GTM teams seamless access to rich B2B data dir",
    url: "https://gateway.demandbase.com/mcp/servers/db-mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/demandbase.com",
    learnMoreUrl: "https://developer.demandbase.com/docs/mcp",
  },
  {
    slug: "home-mcp-server",
    name: "エネチェンジ Home 電気・ガス比較",
    description:
      "日本国内の電気料金プランを比較できます。 お住まいの地域と世帯人数を入力するだけで、利用可能な電力プランの年間電気代の目安を確認できます。  複数のプランを比較しながら、料金の違いや特徴を把握できます。 結果から、プラン",
    url: "https://enechange.jp/api/apps_in_chatgpt/v1/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/enechange.jp",
    learnMoreUrl: "https://enechange.jp/llms.txt",
  },
  {
    slug: "formbyte-mcp-server",
    name: "Formbyte",
    description:
      "Jump-start form creation inside ChatGPT. Ask Formbyte to whip up surveys, signup forms, polls—then refine or a",
    url: "https://formbyte.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/formbyte.ai",
    learnMoreUrl: "https://formbyte.ai/.well-known/oauth-authorization-server",
  },
  {
    slug: "garchi-mcp-server",
    name: "Garchi",
    description:
      "Garchi CMS is a headless SaaS CMS used to manage content across platforms such as websites and apps. With this",
    url: "https://garchi.co.uk/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/garchi.co.uk",
    learnMoreUrl: "https://garchi.co.uk/mcp-docs",
  },
  {
    slug: "jinko-mcp-server-documented-endpoint",
    name: "Jinko MCP server (documented endpoint)",
    description:
      "Jinko helps you find the best flight deals for your next trip.  With Jinko, get flight recommendations based o",
    url: "https://mcp.builders.gojinko.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/gojinko.com",
    learnMoreUrl: "https://docs.gojinko.com/connect/mcp",
  },
  {
    slug: "habitify-mcp-server",
    name: "Habitify",
    description:
      "Build better routines and stay accountable directly within ChatGPT. The Habitify app integrates your habit-tra",
    url: "https://mcp.habitify.me/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/habitify.me",
    learnMoreUrl: "https://api-docs.habitify.me/mcp/",
  },
  {
    slug: "kokiko-mcp-server",
    name: "Kokiko",
    description:
      "Search and compare beauty and personal care products from the Kokiko catalog directly in ChatGPT. Enter a prod",
    url: "https://kokiko.idoctor.md/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/idoctor.md",
    learnMoreUrl: "https://kokiko.idoctor.md/mcp",
  },
  {
    slug: "jimdo-mcp-server",
    name: "Jimdo",
    description:
      "Jimdo builds your professional small business website directly from what you've already discussed with ChatGPT",
    url: "https://website-creation-mcp.e.jimdo.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/jimdo.com",
    learnMoreUrl:
      "https://www.jimdo.com?utm_source=chatgpt&utm_medium=app-store",
  },
  {
    slug: "kubera-mcp-server-v1",
    name: "Kubera MCP Server v1",
    description:
      "Ask questions about your Kubera portfolio. Connect your Kubera account to ask questions about your net worth,",
    url: "https://api.kubera.com/api/v1/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/kubera.com",
    learnMoreUrl: "https://help.kubera.com/article/167-kubera-mcp-config",
  },
  {
    slug: "highlevel-mcp-server",
    name: "HighLevel",
    description:
      "HighLevel gives agencies a unified CRM, automation, and client communication platform. This connector lets you",
    url: "https://services.leadconnectorhq.com/mcp/chatgpt",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/leadconnectorhq.com",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://marketplace.leadconnectorhq.com/docs/other/mcp",
  },
  {
    slug: "lovable-mcp-server",
    name: "Lovable",
    description:
      "Lovable is an AI software creation platform designed specifically for people with no technical experience, giv",
    url: "https://api.lovable.dev/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/lovable.dev",
    learnMoreUrl: "https://docs.lovable.dev/integrations/lovable-mcp-server",
  },
  {
    slug: "zzaim-mcp-server",
    name: "ZZAIM",
    description:
      "ZZAIM gives ChatGPT access to Korea's national curriculum standards — the official learning objectives Korean",
    url: "https://lovelymango-zzaim-mcp.hf.space/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/lovelymango-zzaim-mcp.hf.space",
    learnMoreUrl: "https://zzaim.vercel.app",
  },
  {
    slug: "lytical-mcp-server",
    name: "Lytical",
    description:
      "Lytical automatically captures website activity and turns it into useful insights so you can understand traffi",
    url: "https://mcp.lytical.ai",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/lytical.ai",
    learnMoreUrl: "https://www.lytical.ai/docs/mcp-server",
  },
  {
    slug: "mapify-mcp-server",
    name: "Mapify",
    description:
      "Mapify renders structured content as interactive, visual mind maps. Describe any topic or provide organized in",
    url: "https://mapify.so/mcp",
    transport: "http",
    authType: "header",
    icon: "https://integrations.sh/logo/mapify.so",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://github.com/xmindltd/mapify-mcp-server",
  },
  {
    slug: "how-to-student-mcp-server",
    name: "How To Student",
    description:
      "How To Student is an AI-powered ACT prep app that helps students study smarter, not longer. Get clear explanat",
    url: "https://mcp-hnh4eph34q-uc.a.run.app/mcp",
    transport: "sse",
    authType: "none",
    icon: "https://integrations.sh/logo/mcp-hnh4eph34q-uc.a.run.app",
    learnMoreUrl: "https://tedix.dev/apps/how-to-student/",
  },
  {
    slug: "mentirosa-mcp-server",
    name: "Mentirosa",
    description:
      "Test your human intuition in Mentirosa, a fast-paced language game where you distinguish AI-generated phrases",
    url: "https://mentirosa.vercel.app/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/mentirosa.vercel.app",
    learnMoreUrl: "https://mentirosa.vercel.app/",
  },
  {
    slug: "neurnav-mcp-server",
    name: "Neurnav",
    description:
      "Neurnav helps you manage long-form documents—like research notes and reports—with Git-style workflows inside C",
    url: "https://neurnav.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/neurnav.com",
    learnMoreUrl: "https://neurnav.com/",
  },
  {
    slug: "nexafin-mcp-server-nexafin-com",
    name: "Nexafin MCP server (nexafin.com)",
    description:
      "Nexafin is an AI-powered personal finance and expense tracking assistant that helps you understand your spendi",
    url: "https://nexafin.com/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/nexafin.com",
    learnMoreUrl: "https://nexafin.gitbook.io/api/mcp/mcp",
  },
  {
    slug: "phish-in-mcp",
    name: "Phish.in",
    description:
      "Phish.in is a free archive of live Phish audience recordings. This legal open source site is carefully maintai",
    url: "https://phish.in/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/phish.in",
    learnMoreUrl: "https://phish.in/api-docs",
  },
  {
    slug: "policynote-mcp-server",
    name: "PolicyNote",
    description:
      "Use the PolicyNote app to access structured policy and regulatory intelligence from around the world. Search l",
    url: "https://data.policynote.com/v0/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/policynote.com",
    learnMoreUrl: "https://data.policynote.com/docs/",
  },
  {
    slug: "priority-guardian-mcp-server",
    name: "Priority Guardian",
    description:
      "Priority Guardian — Your priorities deserve more than good intentions.  Protected Time, Flexible Planning: Pri",
    url: "https://pg.priority-guard.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/priority-guard.com",
    learnMoreUrl: "https://pg.priority-guard.com/mcp",
  },
  {
    slug: "replit-mcp-server",
    name: "Replit",
    description:
      "Replit app in ChatGPT lets you build real web or mobile apps just by describing what you want with prompts in",
    url: "https://replit-mcp.com/server/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/replit-mcp.com",
    learnMoreUrl: "https://docs.replit.com/platforms/mcp-server",
  },
  {
    slug: "savecraft-mcp-server",
    name: "Savecraft",
    description:
      "Savecraft connects your actual game save data to ChatGPT. Instead of describing your character, gear, and prog",
    url: "https://mcp.savecraft.gg",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/savecraft.gg",
    learnMoreUrl: "https://savecraft.gg/docs",
  },
  {
    slug: "semrush-mcp-server",
    name: "Semrush",
    description:
      "The Semrush MCP provides structured, quantitative SEO and traffic data for domains, keywords, backlinks, and m",
    url: "https://mcp.semrush.com/openai/v1/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/semrush.com",
    learnMoreUrl: "https://developer.semrush.com/api/introduction/semrush-mcp/",
  },
  {
    slug: "simply-family-budget-mcp-server",
    name: "Simply Family Budget",
    description:
      "Most budgeting tools show you your balance as it is today.  But in real life, money doesn't work that way. Sal",
    url: "https://mcp.simply-family-budget.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/simply-family-budget.com",
    learnMoreUrl: "https://simply-family-budget.com/",
  },
  {
    slug: "symbol-mcp-server",
    name: "Symbol",
    description:
      "Symbol is a structured knowledge base that lets you and your team store important work details (client info, b",
    url: "https://mcp.symbol.chat/mcp",
    transport: "sse",
    authType: "header",
    icon: "https://integrations.sh/logo/symbol.chat",
    headerKey: "Authorization",
    headerPlaceholder: "Bearer <token>",
    learnMoreUrl: "https://symbol.chat/docs/mcp",
  },
  {
    slug: "tuio-mcp-server",
    name: "Tuio",
    description:
      "**Tuio Home Insurance Explorer** provides a transparent way to view and understand Tuio home insurance options",
    url: "https://tuio-mcp-demo.vercel.app/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/tuio-mcp-demo.vercel.app",
    learnMoreUrl: "https://tuio-mcp-demo.vercel.app/mcp",
  },
  {
    slug: "sueldoneto-mcp-server",
    name: "SueldoNeto",
    description:
      "Calcula tu salario neto a partir del bruto en España. Introduce tu salario anual y obtén un desglose visual co",
    url: "https://tusalario.app/mcp",
    transport: "http",
    authType: "none",
    icon: "https://integrations.sh/logo/tusalario.app",
    learnMoreUrl: "https://tusalario.app",
  },
  {
    slug: "veed-fabric-mcp",
    name: "VEED Fabric",
    description:
      "Create AI talking-head videos with VEED Fabric. Browse available characters and voices, preview generation par",
    url: "https://www.veed.io/api/v1/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/veed.io",
    learnMoreUrl:
      "https://veedstudio.github.io/veed-fabric-mcp/authentication.html",
  },
  {
    slug: "vivin-mcp-server",
    name: "Vivin",
    description:
      "Vivin adds a visual companion to your ChatGPT chats. It displays expressions during conversations to match the",
    url: "https://vivin.ai/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/vivin.ai",
    learnMoreUrl: "https://vivin.ai/mcp",
  },
  {
    slug: "whimsical-remote-mcp",
    name: "Whimsical Remote",
    description:
      "Whimsical is the whiteboard for thinking and planning. It’s built for teams to move from chaos to clarity and",
    url: "https://mcp.whimsical.com/mcp",
    transport: "http",
    authType: "oauth",
    icon: "https://integrations.sh/logo/whimsical.com",
    learnMoreUrl: "https://whimsical.com/learn/integrations/remote-mcp",
  },
]
